-- AlterTable
ALTER TABLE "Contact" ALTER COLUMN "phoneNumber" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "GeneralConfiguration" ALTER COLUMN "phone" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Owner" ALTER COLUMN "phoneNumber" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "phone" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "officePhone" SET DATA TYPE DOUBLE PRECISION;
