version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/api-realstate/
hooks:
  ApplicationStart:
    - location: /scripts/start_server.sh
      timeout: 500
      runas: root
  ApplicationStop:
    - location: /scripts/stop_server.sh
      timeout: 500
      runas: root
