# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - n 16.3.0
      - sed -i 's/orbi48_base_dev/orbi48_base/g' .env
      - npm install -g npm@7.22.0
      - node -v
      - npm -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm i
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - '**/*'
  enable-symlinks: yes
