version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: realstate-postgres
    environment:
      POSTGRES_DB: realstate_db
      POSTGRES_USER: realstate
      POSTGRES_PASSWORD: realstate123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - realstate-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U realstate -d realstate_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: realstate-api
    ports:
      - "${API_PORT:-3001}:5000"
    environment:
      - DATABASE_URL=postgresql://realstate:realstate123@postgres:5432/realstate_db
      - JWT_SECRET=realstate-local-secret-key-2024
      - TOKEN_VALIDITY_TIME=24
      - TOKEN_VALIDITY_UNITS=h
      - REFRESH_TOKEN_VALIDITY_TIME=7
      - REFRESH_TOKEN_VALIDITY_UNITS=d
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - PORT=5000
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - realstate-network
    command: npm run start:dev
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  realstate-network:
    driver: bridge